export enum NAVIGATORS {
  EXPLORE_TABS = 'EXPLORE_TABS',
  HOME_STACK = 'HOME_STACK',
  MAIN_TABS = 'MAIN_TABS',
  MONEY_STACK = 'MONEY_STACK',
  PROFILE_STACK = 'PROFILE_STACK',
  ROOT_STACK = 'ROOT_STACK',
  SIGNUP_STACK = 'SIGNUP_STACK',
}
